### ISSUE TITLE
goerp和pms/db  造成不能运行和go get 

### ISSUE THREAD

**Issue by nwaycn** [itcloudy/ERP#5]
2017/03/11 20:05:50 [INFO] Start building...
main.go:6:2: cannot find package "goERP/init" in any of:
        d:\GO\src\src\github.com\hexiaoyun128\ERP\vendor\goERP\init (vendor tree)
        C:\Go\src\goERP\init (from $GOROOT)
        d:\GO\src\src\goERP\init (from $GOPATH)
        E:\works\NwayConference\src\goERP\init
main.go:7:2: cannot find package "goERP/models" in any of:
        d:\GO\src\src\github.com\hexiaoyun128\ERP\vendor\goERP\models (vendor tree)
        C:\Go\src\goERP\models (from $GOROOT)
        d:\GO\src\src\goERP\models (from $GOPATH)
        E:\works\NwayConference\src\goERP\models
main.go:8:2: cannot find package "goERP/routers" in any of:
        d:\GO\src\src\github.com\hexiaoyun128\ERP\vendor\goERP\routers (vendor tree)
        C:\Go\src\goERP\routers (from $GOROOT)
        d:\GO\src\src\goERP\routers (from $GOPATH)
        E:\works\NwayConference\src\goERP\routers
main.go:10:2: cannot find package "goERP/utils" in any of:
        d:\GO\src\src\github.com\hexiaoyun128\ERP\vendor\goERP\utils (vendor tree)
        C:\Go\src\goERP\utils (from $GOROOT)
        d:\GO\src\src\goERP\utils (from $GOPATH)
        E:\works\NwayConference\src\goERP\utils
2017/03/11 20:05:50 [ERRO] ============== Build failed ===================

当我尝试go get goerp时，发生以下问题
D:\Go\src\src\github.com\hexiaoyun128\ERP>go get github.com/hexiaoyun128/goERP
package pms/db: unrecognized import path "pms/db" (import path does not begin with hostname)
package pms/init: unrecognized import path "pms/init" (import path does not begin with hostname)
package pms/routers: unrecognized import path "pms/routers" (import path does not begin with hostname)

**Comment by itcloudy** [comment]
请使用erp仓库的，clone时本地文件夹名改为goERP
